# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beamlit < Formula
  desc ""
  homepage "https://www.beamlit.com"
  version "0.0.36"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.36/beamlit_Darwin_x86_64.tar.gz"
      sha256 "76776f87a741f5e4cfe9a5f439f0891275561f6204ab49a04f056b85424959c3"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.36/beamlit_Darwin_arm64.tar.gz"
      sha256 "1318b550f7bbcb894ffa61acdb61981e98399220eda141a881bd583345c516f6"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.36/beamlit_Linux_x86_64.tar.gz"
        sha256 "5c81b3deb9ab53151a47d841a9672386861256bea3dbfda93573c81be39da63c"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.36/beamlit_Linux_arm64.tar.gz"
        sha256 "9186a8c99cd4c4eda8b7541825f84b2f577c307c39612a443697d952bd29ff39"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Beamlit is a tool to ship AI agents that never slack.
    EOS
  end
end
