# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beamlit < Formula
  desc ""
  homepage "https://www.beamlit.com"
  version "0.0.18"

  on_macos do
    on_intel do
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.18/beamlit_Darwin_x86_64.tar.gz"
      sha256 "5daeb1e3b7851b30e1c1c828d56d6e20307e682549f5c5578dfe950705024d4f"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
    on_arm do
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.18/beamlit_Darwin_arm64.tar.gz"
      sha256 "de43a0cb3237d310433ec7d3a10a08618c3ac453f95732bb0f2955f4a239f4ab"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.18/beamlit_Linux_x86_64.tar.gz"
        sha256 "a0dc8195dfc7c0ea97ea3b71711ab272adc327a881257c030e9c84d2416bb265"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.18/beamlit_Linux_arm64.tar.gz"
        sha256 "f836771417144984ce1aee9d9c22ac043adfb3efe714d2482de672d67bded1e7"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Beamlit is a tool to ship AI agents that never slack.
    EOS
  end
end
