# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beamlit < Formula
  desc ""
  homepage "https://www.beamlit.com"
  version "0.0.57"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.57/beamlit_Darwin_x86_64.tar.gz"
      sha256 "2fde90438832977eda1e8ca7c0cf9cfb56d9263204a04973174ea6b25701dec7"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beamlit/toolkit/releases/download/v0.0.57/beamlit_Darwin_arm64.tar.gz"
      sha256 "ced45e1403901a4e7c186b63e5c9dbf51a38bd05b279e1c89a30ab8740802f00"

      def install
        bin.install "beamlit"
        bin.install_symlink "beamlit" => "bl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.57/beamlit_Linux_x86_64.tar.gz"
        sha256 "2f241f2462513512637a18487f05af81052a99ae9ad7a6e32c199382b7b2d623"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/beamlit/toolkit/releases/download/v0.0.57/beamlit_Linux_arm64.tar.gz"
        sha256 "aa910778b94e9933ff3ac1c299c30933ec934b92b091b258a6a5d31e9faae9a6"

        def install
          bin.install "beamlit"
          bin.install_symlink "beamlit" => "bl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Beamlit is a tool to ship AI agents that never slack.
    EOS
  end
end
